//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Single p_haptx_HxProgressSimulatedPose;
        
        private static SteamVR_Action_Boolean p_haptx_HxNextSimulatedPose;
        
        private static SteamVR_Action_Boolean p_haptx_HxPreviousSimulatedPose;
        
        public static SteamVR_Action_Single haptx_HxProgressSimulatedPose
        {
            get
            {
                return SteamVR_Actions.p_haptx_HxProgressSimulatedPose.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean haptx_HxNextSimulatedPose
        {
            get
            {
                return SteamVR_Actions.p_haptx_HxNextSimulatedPose.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean haptx_HxPreviousSimulatedPose
        {
            get
            {
                return SteamVR_Actions.p_haptx_HxPreviousSimulatedPose.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.haptx_HxProgressSimulatedPose,
                    SteamVR_Actions.haptx_HxNextSimulatedPose,
                    SteamVR_Actions.haptx_HxPreviousSimulatedPose};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.haptx_HxProgressSimulatedPose,
                    SteamVR_Actions.haptx_HxNextSimulatedPose,
                    SteamVR_Actions.haptx_HxPreviousSimulatedPose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.haptx_HxNextSimulatedPose,
                    SteamVR_Actions.haptx_HxPreviousSimulatedPose};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.haptx_HxProgressSimulatedPose};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.haptx_HxProgressSimulatedPose,
                    SteamVR_Actions.haptx_HxNextSimulatedPose,
                    SteamVR_Actions.haptx_HxPreviousSimulatedPose};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_haptx_HxProgressSimulatedPose = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/haptx/in/HxProgressSimulatedPose")));
            SteamVR_Actions.p_haptx_HxNextSimulatedPose = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/haptx/in/HxNextSimulatedPose")));
            SteamVR_Actions.p_haptx_HxPreviousSimulatedPose = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/haptx/in/HxPreviousSimulatedPose")));
        }
    }
}
